### ISSUE TITLE
Verge Tordroid V2.3 shows 'No connection'

### ISSUE THREAD

**Issue by espiritudeltiempo** [vergecurrency/tordroid#17]
I am using a REDMI Android phone and I have installed the latest Orbot Version, my Verge Tordroid V2.3 is checked as a Tor-Enabled App and my Orbot App is connected to the Tor Network.

I am not able to connect my verge wallet and it shows a balance of 0. 
I reinstalled the apps, unabled and enabled the App in Orbot but nothing helped me so far.

Asking for help to solve this issue. Thank you!

![Screenshot_2024-02-13-16-32-02-998_com vergepay wallet](https://github.com/vergecurrency/tordroid/assets/159960968/8c2ff5ec-ca10-489f-9e03-3fa351439923)

**Comment by justinvforvendetta** [comment]
and you are sure that the address you see in "receive" has a balance when you check on https://verge-blockchain.info/ ?

also it should not have to have a check mark in vpn section of orbot.

**Comment by justinvforvendetta** [comment]
should not need vpn mode. this wallet has connected before?

**Comment by espiritudeltiempo** [comment]
yes the wallet was connected back in october 2023 and I was able to see the correct balance. I didn't open the wallet for the last months and as i opened it again yesterday I saw the correct balance for a brief moment before it showed me no connection anymore and a balance of 0...

**Comment by justinvforvendetta** [comment]
nothing has changed on the back end, have you made any changes?

**Comment by espiritudeltiempo** [comment]
No I didn't change anything since then. I am just not able to connect my wallet anymore.

**Comment by justinvforvendetta** [comment]
orbot is up to date?

**Comment by justinvforvendetta** [comment]
must have to do with orbot then. try swiping down and waiting for connection, with vpn disabled, enabled, etc

**Comment by espiritudeltiempo** [comment]
I tried several ways (with vpn disabled, enabled, etc) but still no connection of my wallet. I want to add that I did the transactions in October 2022 not as I said in 2023. So maybe something changed with the app during this time?

**Comment by justinvforvendetta** [comment]
no, but if you are not connecting something is wrong on your orbot. i can connect on my android, and i see the android server is online here: https://1209k.com/bitcoin-eye/ele.php?chain=xvg  (7eagtn6nsmlyjhjv647ejj4j4orgb2cotoc5dl73qpamhvbvioao4zad.onion is android)

**Comment by justinvforvendetta** [comment]
btw, orbot has a log and should tell you what the problem is after trying to connect with the verge app

**Comment by espiritudeltiempo** [comment]
Finally I just downloaded Coinomi and recreated my Verge wallet with my seed phrase and now this wallet is working without any problems.
