### ISSUE TITLE
PLEASE HELP-I LOST PAYMENT PASSWORD!  AJUDEM! PERDI A SENHA DE PAGAMENTOS!

### ISSUE THREAD

**Issue by Rgringo** [vergecurrency/tordroid#18]
TEXT IN PORTUGUESE AND ENGLISH (SORT AFTER)
TEXTO EM PORTUGUÊS AND ENGLISH (LOGO APÓS)

 AJUDEM POR FAVOR

 Bom dia. Estou sem conseguir enviar minhas Verges para outra carteira. Já coloquei o endereço da  carteira para a qual pretendo enviar, mas ele pede uma senha e eu coloquei o **PIN de 4 números que escolhi para a carteira Verge Oficial (Android) e a carteira não aceita**, diz que está errado. 👉 Mas diz que eu posso restaurar a carteira mas que eu perderia as moedas se não tivesse feito back UP da Frase de Recuperação (Semente). Só que eu não sei o que ele quer dizer com back UP: Quer dizer fazer aquele procedimento criptografado de cópia de arquivos ou quer dizer simplesmente por back UP da Frase de Recuperação: o ato de copiar com caneta e papel essa frase ? Essa falta de clareza me faz hesitar em mandar restaurar a carteira, pois se back UP a que se refere significa copiar algum arquivo específico e não a simples frase de recuperação (usando papel e caneta), poderei perder todas as moedas. Sejam claros por favor! Além do mais, gostaria de saber se ao restaurar a carteira usando a frase de recuperação, poderei escolher uma nova senha, ou continuará bloqueado exigindo a senha antiga que não sei qual é....

PLEASE HELP, good morning.  I am unable to send my Verges to another wallet.  I have already entered the address of the wallet I intend to send it to, but it asks for a password and I entered the 4-number PIN that I chose for the Official Verge wallet (Android) and the wallet does not accept it, it says it is wrong.  👉 But it says that I can restore the wallet but that I would lose the coins if I hadn't backed up the Recovery Phrase (Seed).  But I don't know what he means by back UP: Does he mean doing that encrypted file copying procedure or does he simply mean back UP of the Recovery Phrase: the act of copying that phrase with pen and paper?  This lack of clarity makes me hesitate to have the wallet restored, because if the back UP you are referring to means copying a specific file and not the simple recovery phrase (using paper and pen), I could lose all the coins.  Please be clear!  Furthermore, I would like to know if when restoring the wallet using the recovery phrase, I will be able to choose a new password, or will it continue to be blocked requiring the old password which I don't know what it is....
![Screenshot_20240226_063747](https://github.com/vergecurrency/tordroid/assets/161302553/855e1f43-5bfc-49ec-be18-1743f863fd20)
![Screenshot_20240226_063545](https://github.com/vergecurrency/tordroid/assets/161302553/1088553c-bd15-4702-b84d-7e72acdea0db)

**Comment by justinvforvendetta** [comment]
just use the special random words it told you to write down when you first installed the application on your phone
